package org.domainobject.foo;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import org.domainobject.core.Column;

public class OracleTest {

	/**
	 * @param args
	 * @throws Exception
	 */
	public static void main(String[] args) throws Exception
	{
		List<Column> list = new ArrayList<Column>();

		Connection conn;
		String sql;

		// Oracle:
//						Class.forName("oracle.jdbc.OracleDriver");
//						conn = DriverManager.getConnection("jdbc:oracle:thin:AYCO/AYCO@localhost:1521:XE");
//						sql = "INSERT INTO EMP(ID,NAME)VALUES(EMP_SEQ.NEXTVAL,'Ayco Holleman')";

		// MySQL:
//				Class.forName("com.mysql.jdbc.Driver");
//				conn = DriverManager.getConnection("jdbc:mysql://localhost/domainobject", "root", null);
//				sql = "INSERT INTO EMP(ID,NAME)VALUES(NULL,'Ayco Holleman')";

		// HSQLDB
		new org.hsqldb.jdbc.JDBCDriver();
		Class.forName("org.hsqldb.jdbc.JDBCDriver");
		conn = DriverManager.getConnection("jdbc:hsqldb:file:/C:/tmp/hsqldb/test", "root", "");

		DatabaseMetaData dbmd = conn.getMetaData();
		System.out.println("vendor: " + dbmd.getDatabaseProductName());
		System.out.println("major version: " + dbmd.getDatabaseMajorVersion());
		System.out.println("minor version: " + dbmd.getDatabaseMinorVersion());
		System.out.println("driver name: " + dbmd.getDriverName());
		System.out.println("driver major: " + dbmd.getDriverMajorVersion());
		System.out.println("driver minor: " + dbmd.getDriverMinorVersion());
		// see: http://info.michael-simons.eu/2007/10/09/jdbc-get-autogenerated-keys-on-a-oracle-db/
		// http://docs.oracle.com/cd/B28359_01/java.111/b31224/jdbcvers.htm#CHDEGDHJ
		//		PreparedStatement stmt = conn.prepareStatement(sql, new String[] { "ID" });
		//		stmt.executeUpdate();
		//		ResultSet rs = stmt.getGeneratedKeys();
		//		if (rs.next()) {
		//			System.out.println("Generated key 1: " + rs.getLong(1));
		//		}
		System.out.println("Done");

	}

}
